### ISSUE TITLE
React-query 사용 환경 구축

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/React-reference#11]
## Summary
React-query 사용 환경 구축

## Todo
- [x] 필수 라이브러리 설치하기
- [x] 가비지 목업 데이터 API 호출 구현
- [x] 데이터 처리 테스트
