### ISSUE TITLE
StoryBook 사용 환경 구축

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/React-reference#4]
## Summary
UI 컴포넌트 별 디자인을 협업환경에서 쉽게 공유하기 위해 스타일북 도입

## Todo
- [x] Storybook 필수 라이브러리 설치
- [x] Storybook 폴더 구조 설정
- [x] Storybook 실제 컴포넌트 UI 테스트 진행
- [x] Storybook 사용 후 문서정리
